### ISSUE TITLE
.bss and .data contiguity

### ISSUE THREAD

**Issue by Ericson2314** [cnc-patch/petool#1]
In https://github.com/cnc-patch/engine2/blob/master/yr/link.lds#L9 I rounded up the size of `.data` so that it reached the end of the alignment (remember alignment size isn't necessarily the same as page size).

Either we don't align `.bss`, or `.data`'s length should be rounded (and .bss shrunk according), and .bss should exist based on whether the _rounded_ length is bigger than the virtual size. Right?

**Comment by hifi** [comment]
Would suggest rounding `.data` and shrinking `.bss` as needed first. It has a weird side effect of there being stuff at the end of `.data` at runtime that shouldn't be there (original merged with no alignment?) unless the MS compiler aligns the appended `.bss` like we would?

Haven't yet found any way to successfully increase the virtual size of .data in linker script, that would be the proper approach.

**Comment by Ericson2314** [comment]
IIRC binutils/libBFD can only handle fully uninitialized or fully initialized sections, so recreating the original section is not an option unless we send them more patches.

Incrementing `.` in an initialized section like `.data` will pad on zeros at the end. This shouldn't be a problem because `.bss` is also 0-initialized.

**Comment by hifi** [comment]
No it's not technically a problem, but it would be odd in a debugger when the end of `.data` is used like `.bss` but `.bss` exists anyway.

**Comment by Ericson2314** [comment]
Well `setvs` to just bump the virtual size gets you the original `.data` without `.bss`.
